services:
  - type: web
    name: flowise-klub
    env: node
    plan: free
    buildCommand: pnpm install --frozen-lockfile && pnpm build
    startCommand: pnpm start
    repo: https://github.com/williamdeosampaio/Flowise
    branch: main
